name = "BarkerMCMC"
uuid = "be4af45d-7920-418d-be3f-405e75a2263c"
authors = ["Andreas Scheidegger <andreas.scheidegger@eawag.ch"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
