name = "BarkerMCMC"
uuid = "be4af45d-7920-418d-be3f-405e75a2263c"
authors = ["Andreas Scheidegger <andreas.scheidegger@eawag.ch"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
ProgressMeter = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
